async page => {
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('light');
  await page.getByRole('button',{name:'My work',exact:true}).click();
  await page.getByRole('button',{name:'Board',exact:true}).click();
  const board=page.locator('div[aria-label="Board"]');
  const cards=await board.locator('h3').allTextContents();
  if(cards.length!==3||!cards.every(t=>t.startsWith('Synthetic')))throw Error('Wrong real assigned task page');
  await page.waitForTimeout(500);
  await page.screenshot({path:'reports/business-intake-ui-evidence/member-board-1280-light.png'});
  await page.getByRole('button',{name:'Table',exact:true}).click();
  const table=page.getByRole('table',{name:'Tasks',exact:true});
  const rows=await table.locator('tbody tr').count();
  if(rows!==3)throw Error('Table changed the authorized task page');
  if(await page.getByRole('button',{name:'Table',exact:true}).getAttribute('aria-pressed')!=='true')throw Error('Table selector is not current');
  await page.waitForTimeout(500);
  await page.screenshot({path:'reports/business-intake-ui-evidence/member-table-1280-light.png'});
  await page.setViewportSize({width:390,height:844});
  const region=page.getByRole('region',{name:'Table',exact:true});
  await region.focus();
  const before=await region.evaluate(el=>el.scrollLeft);
  await page.keyboard.press('ArrowRight');
  await page.waitForTimeout(500);
  const scroll=await region.evaluate(el=>({left:el.scrollLeft,width:el.clientWidth,scrollWidth:el.scrollWidth}));
  if(scroll.left<=before||await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Narrow table keyboard scrolling failed');
  await page.screenshot({path:'reports/business-intake-ui-evidence/member-table-390-light.png'});
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('button',{name:'Workspace appearance',exact:true}).click();
  const colors=page.getByRole('combobox',{name:'Workspace colors',exact:true});
  await colors.waitFor();
  const readonly=await colors.isDisabled();
  const saves=await page.getByRole('button',{name:'Save workspace defaults',exact:true}).count();
  if(!readonly||saves!==0)throw Error('Member can edit tenant appearance');
  await page.waitForTimeout(500);
  await page.screenshot({path:'reports/business-intake-ui-evidence/member-appearance-readonly.png'});
  const response=page.waitForResponse(r=>r.url().endsWith('/api/business/intake/bindings/list'));
  await page.getByRole('button',{name:'Sources',exact:true}).click();
  const status=(await response).status();
  await page.getByRole('alert').filter({hasText:'The workspace could not be reached.'}).waitFor();
  if(status!==502)throw Error('Fixture availability changed: '+status);
  const setup=await page.getByRole('button',{name:'Set up a source',exact:true}).count();
  await page.waitForTimeout(500);
  await page.screenshot({path:'reports/business-intake-ui-evidence/member-sources-unavailable.png'});
  return {assignedCards:cards.length,tableRows:rows,narrowTable:scroll,appearanceReadonly:readonly,appearanceSaves:saves,intakeStatus:status,sourceSetupControls:setup,legacyEntry:await page.getByRole('link',{name:'Open engineering workspace',exact:true}).count()};
}
