async page => {
  const fs=page.constructor.constructor('return process')().getBuiltinModule('node:fs');
  const c=JSON.parse(fs.readFileSync('/Users/mohamedadan/projects/_worktrees/ops-desk/tickets/.docs/business-intake-fixtures/unified-YQmRz8/ui-credentials.json','utf8'));
  await page.getByRole('button',{name:'ui: meeting-follow-up',exact:false}).click();
  const passage=page.getByRole('region',{name:'Exact source passage',exact:true});
  await passage.getByRole('checkbox',{name:'Exact source passage 1',exact:true}).check();
  const selectedText=await passage.locator('li').first().innerText();
  const created=page.waitForResponse(r=>r.url().endsWith('/intake/candidates/create')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Prepare private draft',exact:true}).click();
  const createdResponse=await created;
  if(createdResponse.status()!==200)throw Error('Passage selection failed');
  const candidate=await createdResponse.json();
  const editor=page.getByRole('region',{name:'Private task draft',exact:true});
  await editor.getByLabel('Task title',{exact:true}).fill('Synthetic UI: agree onboarding response');
  await editor.getByLabel('Brief',{exact:true}).fill('Confirm the onboarding response with the customer. This deliberately written shared brief does not copy the private transcript.');
  await editor.getByLabel('Due date',{exact:true}).fill('2026-11-02');
  await editor.getByLabel('Assigned to',{exact:true}).selectOption(c.sessions.manager.memberId);
  await editor.getByLabel('Reviewer',{exact:true}).selectOption(c.sessions.owner.memberId);
  await editor.getByLabel('Owner mentioned in source (optional)',{exact:true}).fill('Confirm with the human owner; suggestion only.');
  await editor.getByLabel('Deadline mentioned in source (optional)',{exact:true}).fill('After the meeting; suggestion only.');
  await page.screenshot({path:'reports/business-intake-ui-evidence/unified-private-draft-1280-light.png'});
  const saved=page.waitForResponse(r=>r.url().endsWith('/intake/candidates/edit')&&r.request().method()==='POST');
  await editor.getByRole('button',{name:'Save private draft',exact:true}).click();
  const savedResponse=await saved;
  if(savedResponse.status()!==200)throw Error('Private draft save failed');
  const review=editor.getByRole('region',{name:'Review before sharing',exact:true});
  await review.getByRole('heading',{name:'Destination audience: Feedback',exact:true}).waitFor();
  const text=await review.innerText();
  const accept=review.getByRole('button',{name:'Accept into shared work',exact:true});
  const initiallyDisabled=await accept.isDisabled();
  if(!initiallyDisabled||!text.includes('2026-11-02')||!text.includes('Everyone with current or future Read access')||!text.includes('even if the original source')||!text.includes('ui manager'))throw Error('Exact audience/task review missing');
  await page.screenshot({path:'reports/business-intake-ui-evidence/unified-exact-audience-1280-light.png'});
  await review.getByRole('checkbox',{name:'I have reviewed these exact passages',exact:false}).check();
  const accepted=page.waitForResponse(r=>r.url().endsWith('/intake/candidates/accept')&&r.request().method()==='POST');
  await accept.click();
  const acceptedResponse=await accepted;
  if(acceptedResponse.status()!==200)throw Error('Explicit acceptance failed');
  const result=await acceptedResponse.json();
  await page.getByRole('region',{name:'Decision recorded',exact:true}).getByRole('heading',{name:'Task created',exact:true}).waitFor();
  await page.screenshot({path:'reports/business-intake-ui-evidence/unified-accepted-receipt-1280-light.png'});
  await page.getByRole('button',{name:'Open shared task',exact:true}).click();
  await page.getByRole('heading',{name:'Synthetic UI: agree onboarding response',exact:true}).waitFor();
  return {candidateId:candidate.id,selectedOriginalPassage:selectedText.includes('ui private evidence revision one'),selectStatus:createdResponse.status(),draftStatus:savedResponse.status(),acceptInitiallyDisabled:initiallyDisabled,acceptStatus:acceptedResponse.status(),decision:result.decision.kind,taskId:result.decision.task.taskId,explicitAudience:true};
}
