"use client"

import { useLocale } from "next-intl"

const english = {
  workspace: "Workspace",
  myWork: "My work",
  sharedWork: "Shared work",
  review: "Review",
  team: "People & agents",
  myWorkHint: "What you own and what’s assigned to you.",
  sharedWorkHint: "A shared view of the work your team can access.",
  reviewHint: "Read the deliverable, then make the decision.",
  createTask: "Create task",
  taskTitle: "Task title",
  outcome: "Brief",
  owner: "Accountable owner",
  assignee: "Assigned to",
  reviewer: "Reviewer",
  unassigned: "Unassigned",
  noOwner: "Needs an owner",
  noReviewer: "No reviewer",
  human: "Person",
  agent: "Agent",
  domain: "Area of work",
  priority: "Priority",
  dueDate: "Due date",
  noDate: "No due date",
  allDay: "Calendar date; no time or reminder is set.",
  status: "Status",
  todo: "To do",
  in_progress: "In progress",
  done: "Done",
  cancelled: "Cancelled",
  marketing: "Marketing",
  channels: "Channels",
  ads: "Ads",
  website: "Website",
  feedback: "Feedback",
  engineering: "Engineering",
  low: "Low",
  normal: "Normal",
  high: "High",
  urgent: "Urgent",
  list: "List",
  board: "Board",
  search: "Find a task",
  allDomains: "All areas",
  allStatuses: "All statuses",
  clearFilters: "Clear filters",
  emptyTitle: "Make the next step clear.",
  emptyHint: "Create a task, name its owner and choose who will do the work.",
  emptyMyTitle: "Your work will appear here.",
  emptyMyHint: "Open shared work to see the tasks available to your team.",
  emptyReviewTitle: "Nothing waiting for your review.",
  emptyReviewHint: "Work submitted for a decision will appear here.",
  noResults: "No tasks match these filters.",
  noResultsHint: "Try another area or status, or clear the filters.",
  emptyColumn: "No tasks here",
  loading: "Loading your workspace…",
  refresh: "Refresh",
  retry: "Try again",
  close: "Close",
  back: "Back to work",
  save: "Save changes",
  saving: "Saving…",
  cancel: "Cancel",
  edit: "Edit task",
  assignment: "Responsibility",
  activity: "Activity",
  notes: "Notes",
  addNote: "Add note",
  noteHint: "Share an update with everyone who can access this task.",
  deliverable: "Deliverable",
  submitReview: "Submit for review",
  accept: "Accept work",
  returnWork: "Return for changes",
  reviewComment: "Review note",
  startWork: "Start work",
  returnTodo: "Move to To do",
  cancelTask: "Cancel task",
  archive: "Archive task",
  updated: "Updated",
  created: "Created",
  creator: "Created by",
  readOnly: "View only",
  readOnlyHint:
    "You can read this work. Your current access does not allow changes.",
  conflict: "This task changed while you were editing.",
  conflictHint:
    "Your draft is kept here. Load the current task and compare before saving again.",
  loadCurrent: "Load current task",
  currentVersion: "Current saved version",
  keepDraft: "Use my draft with this version",
  discardDraft: "Discard my draft",
  unsaved: "Unsaved changes",
  discardTitle: "Discard these changes?",
  discardHint: "Your unsaved text will be removed from this window.",
  stay: "Keep editing",
  saved: "Changes saved",
  offline: "The workspace could not be reached.",
  offlineHint:
    "Check your connection, then try again. Unsaved work stays in this window.",
  forbidden: "Your access does not allow this action.",
  notFound: "This task is unavailable or you no longer have access.",
  invalid: "Check the task fields and try again.",
  signIn: "Sign in to your workspace",
  signInHint:
    "Use the personal access your organization administrator provided.",
  server: "Workspace address",
  memberToken: "Personal access token",
  connect: "Connect",
  connecting: "Connecting…",
  disconnect: "Disconnect",
  sessionExpired: "Your access has expired or was revoked.",
  signInAgain: "Sign in again",
  operator: "Administrator access",
  openEngineering: "Open engineering workspace",
  operatorHint:
    "Engineering and agent conversations require the existing administrator connection.",
  language: "Language",
  appearance: "Appearance",
  light: "Light",
  dark: "Dark",
  menu: "Open workspace navigation",
  connected: "Connected",
  loadedTasks: "tasks loaded",
  more: "Load more",
  synthetic: "Synthetic workspace",
  signInTitle: "Give shared work a clear next step.",
  signInLead:
    "People and agents work from the same brief. Responsibility stays visible, and completed work comes back for a human decision.",
  sessionHint:
    "Access is kept in this window only. Reloading requires signing in again.",
  addressHint:
    "Use the HTTPS address of your organization's Desk, or a local loopback server.",
  operatorToken: "Original administrator token",
  existingOperator: "Use this browser’s administrator connection",
  localDesk: "Use this desktop’s local workspace",
  localLabel: "Local desktop",
  bootstrapTitle: "Start with your organization.",
  bootstrapHint:
    "Create the shared workspace and name its first accountable owner. Then add people and agents.",
  organizationName: "Organization name",
  yourName: "Your name",
  createWorkspace: "Create workspace",
  teamHint: "Give people and agents explicit access to the work they need.",
  addMember: "Add a person or agent",
  displayName: "Display name",
  kind: "Member type",
  role: "Role",
  roleOwner: "Owner",
  roleAdmin: "Administrator",
  roleManager: "Manager",
  roleMember: "Member",
  roleViewer: "Viewer",
  domainsHint:
    "Choose explicit areas of access. Assignment does not grant access to another area.",
  active: "Active",
  revoked: "Revoked",
  protectedOwner: "Original workspace owner",
  memberAccess: "Member access",
  memberAccessHint:
    "Changes apply to the member’s next protected request. Revoking a member ends all of their personal sessions.",
  revokeMember: "Revoke member access",
  credentials: "Personal access",
  credentialLabel: "Access label",
  issueCredential: "Create personal access token",
  revokeCredential: "Revoke token",
  noCredentials: "No personal access tokens.",
  agentAccessHint:
    "Agents contribute through a task’s authorized engineering execution. Agent entries do not receive human sign-in tokens.",
  secretTitle: "Share this access token privately.",
  secretHint:
    "It is shown once. Copy it intentionally and share it with this person through your existing secure channel. Closing removes it from this window.",
  reveal: "Reveal token",
  hide: "Hide token",
  copy: "Copy token",
  copied: "Copied",
  copyFailed: "Copy was unavailable. Reveal and copy the token manually.",
  finishToken: "I have saved it; close",
  confirmRevoke: "Revoke this access?",
  confirmRevokeHint:
    "New requests using this access will be refused. This does not delete task history.",
  revoke: "Revoke access",
  revisionHint:
    "Access changed elsewhere. Reload the current member before editing again.",
  noMembers: "No members are available in your areas of work.",
  memberUnavailable: "Member unavailable",
  anyReviewer: "Any authorized human reviewer",
  reviewerHint: "Only a person with review access can accept completed work.",
  assignmentHint:
    "An owner is accountable for the result. The assignee does the work; a person reviews it.",
  createdTask: "Task created",
  submitHint:
    "Describe the result for your reviewer. This is shared with everyone who can access the task.",
  reviewWithoutDeliverable:
    "No deliverable was attached. Review the brief and activity before deciding.",
  reviewedTask: "I have reviewed this task and its current deliverable.",
  briefEmpty: "No brief added.",
  activityEmpty: "No activity to show.",
  archived: "Archived",
  restore: "Restore from archive",
  archiveHint: "The task leaves active lists. Its history is retained.",
  workChanged: "Task updated",
  noteAdded: "Added a note",
  delivered: "Submitted work for review",
  assigned: "Updated responsibility",
  reviewed: "Reviewed work",
  execution: "Engineering detail",
  executionLinked: "Linked engineering work",
  executionInactive: "This execution is no longer active.",
  linkExecution: "Link existing engineering work",
  workTaskId: "Existing engineering task number",
  linkHint:
    "Link an already active execution for the assigned agent. This does not launch a conversation or model.",
  noExecution:
    "No engineering execution is linked. People can complete this work directly.",
  sourceVersion: "Revision",
  refreshBeforeRetry:
    "The save could not be confirmed. Refresh the work list before trying another creation.",
} as const

export type BusinessCopy = { [K in keyof typeof english]: string }
const arabic: BusinessCopy = {
  workspace: "مساحة العمل",
  myWork: "عملي",
  sharedWork: "العمل المشترك",
  review: "المراجعة",
  team: "الأشخاص والوكلاء",
  myWorkHint: "العمل الذي تتولى مسؤوليته أو أُسند إليك.",
  sharedWorkHint: "العمل المشترك الذي يستطيع فريقك الوصول إليه.",
  reviewHint: "اقرأ المخرجات ثم اتخذ القرار.",
  createTask: "إنشاء مهمة",
  taskTitle: "عنوان المهمة",
  outcome: "وصف العمل",
  owner: "المسؤول عن النتيجة",
  assignee: "المكلّف بالعمل",
  reviewer: "المراجع",
  unassigned: "غير مسندة",
  noOwner: "تحتاج إلى مسؤول",
  noReviewer: "لم يُحدد مراجع",
  human: "شخص",
  agent: "وكيل",
  domain: "مجال العمل",
  priority: "الأولوية",
  dueDate: "تاريخ الاستحقاق",
  noDate: "بلا تاريخ استحقاق",
  allDay: "تاريخ فقط؛ لم يُحدد وقت أو تذكير.",
  status: "الحالة",
  todo: "للتنفيذ",
  in_progress: "قيد التنفيذ",
  done: "مكتملة",
  cancelled: "ملغاة",
  marketing: "التسويق",
  channels: "القنوات",
  ads: "الإعلانات",
  website: "الموقع",
  feedback: "الملاحظات",
  engineering: "الهندسة",
  low: "منخفضة",
  normal: "عادية",
  high: "مرتفعة",
  urgent: "عاجلة",
  list: "قائمة",
  board: "لوحة",
  search: "البحث عن مهمة",
  allDomains: "كل المجالات",
  allStatuses: "كل الحالات",
  clearFilters: "مسح المرشحات",
  emptyTitle: "حدّد الخطوة التالية.",
  emptyHint: "أنشئ مهمة وحدّد المسؤول عنها ومن سينفذها.",
  emptyMyTitle: "سيظهر عملك هنا.",
  emptyMyHint: "افتح العمل المشترك للاطلاع على مهام فريقك.",
  emptyReviewTitle: "لا توجد أعمال تنتظر مراجعتك.",
  emptyReviewHint: "ستظهر هنا الأعمال المقدمة لاتخاذ قرار بشأنها.",
  noResults: "لا توجد مهام تطابق المرشحات.",
  noResultsHint: "جرّب مجالًا أو حالة أخرى، أو امسح المرشحات.",
  emptyColumn: "لا توجد مهام هنا",
  loading: "جارٍ تحميل مساحة العمل…",
  refresh: "تحديث",
  retry: "المحاولة مجددًا",
  close: "إغلاق",
  back: "العودة إلى العمل",
  save: "حفظ التغييرات",
  saving: "جارٍ الحفظ…",
  cancel: "إلغاء",
  edit: "تعديل المهمة",
  assignment: "المسؤولية",
  activity: "النشاط",
  notes: "الملاحظات",
  addNote: "إضافة ملاحظة",
  noteHint: "شارك تحديثًا مع كل من يستطيع الوصول إلى هذه المهمة.",
  deliverable: "مخرجات العمل",
  submitReview: "إرسال للمراجعة",
  accept: "قبول العمل",
  returnWork: "إعادة للتعديل",
  reviewComment: "ملاحظة المراجعة",
  startWork: "بدء العمل",
  returnTodo: "نقل إلى للتنفيذ",
  cancelTask: "إلغاء المهمة",
  archive: "أرشفة المهمة",
  updated: "آخر تحديث",
  created: "تاريخ الإنشاء",
  creator: "أنشأها",
  readOnly: "للعرض فقط",
  readOnlyHint: "يمكنك قراءة هذا العمل. صلاحياتك الحالية لا تسمح بالتعديل.",
  conflict: "تغيّرت المهمة أثناء تعديلك لها.",
  conflictHint:
    "مسودتك محفوظة هنا. حمّل المهمة الحالية وقارنها قبل الحفظ مجددًا.",
  loadCurrent: "تحميل المهمة الحالية",
  currentVersion: "النسخة المحفوظة الحالية",
  keepDraft: "استخدام مسودتي مع هذه النسخة",
  discardDraft: "تجاهل مسودتي",
  unsaved: "تغييرات غير محفوظة",
  discardTitle: "تجاهل هذه التغييرات؟",
  discardHint: "سيُحذف النص غير المحفوظ من هذه النافذة.",
  stay: "متابعة التعديل",
  saved: "حُفظت التغييرات",
  offline: "تعذّر الاتصال بمساحة العمل.",
  offlineHint:
    "تحقق من الاتصال وحاول مجددًا. يبقى العمل غير المحفوظ في هذه النافذة.",
  forbidden: "صلاحياتك لا تسمح بهذا الإجراء.",
  notFound: "المهمة غير متاحة أو لم يعد لديك إذن بالوصول إليها.",
  invalid: "تحقق من حقول المهمة وحاول مجددًا.",
  signIn: "تسجيل الدخول إلى مساحة عملك",
  signInHint: "استخدم بيانات الوصول الشخصية التي زوّدك بها مسؤول مؤسستك.",
  server: "عنوان مساحة العمل",
  memberToken: "رمز الوصول الشخصي",
  connect: "اتصال",
  connecting: "جارٍ الاتصال…",
  disconnect: "قطع الاتصال",
  sessionExpired: "انتهت صلاحية وصولك أو أُلغي.",
  signInAgain: "تسجيل الدخول مجددًا",
  operator: "دخول المسؤول",
  openEngineering: "فتح مساحة الهندسة",
  operatorHint: "تتطلب الهندسة ومحادثات الوكلاء اتصال المسؤول الحالي.",
  language: "اللغة",
  appearance: "المظهر",
  light: "فاتح",
  dark: "داكن",
  menu: "فتح قائمة مساحة العمل",
  connected: "متصل",
  loadedTasks: "مهام محمّلة",
  more: "تحميل المزيد",
  synthetic: "مساحة عمل تجريبية",
  signInTitle: "خطوة تالية واضحة للعمل المشترك.",
  signInLead:
    "يعمل الأشخاص والوكلاء من وصف واحد. تبقى المسؤولية واضحة، ويعود العمل المنجز إلى شخص لاتخاذ القرار.",
  sessionHint:
    "يبقى الوصول في هذه النافذة فقط. يتطلب إعادة تحميل الصفحة تسجيل الدخول مجددًا.",
  addressHint: "استخدم عنوان HTTPS لمساحة مؤسستك، أو خادمًا محليًا.",
  operatorToken: "رمز المسؤول الأصلي",
  existingOperator: "استخدام اتصال المسؤول المحفوظ في هذا المتصفح",
  localDesk: "استخدام مساحة سطح المكتب المحلية",
  localLabel: "سطح المكتب المحلي",
  bootstrapTitle: "ابدأ بمؤسستك.",
  bootstrapHint:
    "أنشئ مساحة العمل المشتركة وحدد مالكها الأول، ثم أضف الأشخاص والوكلاء.",
  organizationName: "اسم المؤسسة",
  yourName: "اسمك",
  createWorkspace: "إنشاء مساحة العمل",
  teamHint: "امنح الأشخاص والوكلاء صلاحيات واضحة للعمل الذي يحتاجون إليه.",
  addMember: "إضافة شخص أو وكيل",
  displayName: "الاسم المعروض",
  kind: "نوع العضو",
  role: "الدور",
  roleOwner: "مالك",
  roleAdmin: "مسؤول",
  roleManager: "مدير",
  roleMember: "عضو",
  roleViewer: "مشاهد",
  domainsHint:
    "حدد مجالات الوصول صراحةً. إسناد المهمة لا يمنح الوصول إلى مجال آخر.",
  active: "نشط",
  revoked: "أُلغي وصوله",
  protectedOwner: "المالك الأصلي لمساحة العمل",
  memberAccess: "صلاحيات العضو",
  memberAccessHint:
    "تسري التغييرات على الطلب المحمي التالي للعضو. إلغاء وصوله ينهي كل جلساته الشخصية.",
  revokeMember: "إلغاء وصول العضو",
  credentials: "الوصول الشخصي",
  credentialLabel: "اسم رمز الوصول",
  issueCredential: "إنشاء رمز وصول شخصي",
  revokeCredential: "إلغاء الرمز",
  noCredentials: "لا توجد رموز وصول شخصية.",
  agentAccessHint:
    "يساهم الوكلاء عبر التنفيذ الهندسي المصرح به للمهمة. لا يحصل الوكلاء على رموز تسجيل دخول بشرية.",
  secretTitle: "شارك رمز الوصول بشكل خاص.",
  secretHint:
    "يُعرض مرة واحدة. انسخه بإرادتك وشاركه مع هذا الشخص عبر قناتك الآمنة المعتادة. إغلاق النافذة يزيله منها.",
  reveal: "إظهار الرمز",
  hide: "إخفاء الرمز",
  copy: "نسخ الرمز",
  copied: "نُسخ",
  copyFailed: "تعذر النسخ. أظهر الرمز وانسخه يدويًا.",
  finishToken: "حفظته؛ إغلاق",
  confirmRevoke: "إلغاء هذا الوصول؟",
  confirmRevokeHint: "ستُرفض الطلبات الجديدة بهذا الوصول. لا يُحذف سجل المهام.",
  revoke: "إلغاء الوصول",
  revisionHint:
    "تغيرت الصلاحيات من مكان آخر. حمّل بيانات العضو الحالية قبل التعديل مجددًا.",
  noMembers: "لا يوجد أعضاء متاحون في مجالات عملك.",
  memberUnavailable: "العضو غير متاح",
  anyReviewer: "أي مراجع بشري مخوّل",
  reviewerHint: "لا يقبل العمل المنجز إلا شخص لديه صلاحية المراجعة.",
  assignmentHint: "المالك مسؤول عن النتيجة. ينفذ المكلّف العمل، ويراجعه شخص.",
  createdTask: "أُنشئت المهمة",
  submitHint:
    "صف النتيجة للمراجع. يطّلع عليها كل من لديه صلاحية الوصول إلى المهمة.",
  reviewWithoutDeliverable:
    "لم تُرفق مخرجات. راجع وصف العمل والنشاط قبل القرار.",
  reviewedTask: "راجعت هذه المهمة ومخرجاتها الحالية.",
  briefEmpty: "لم يُضف وصف للعمل.",
  activityEmpty: "لا يوجد نشاط للعرض.",
  archived: "مؤرشفة",
  restore: "استعادة من الأرشيف",
  archiveHint: "تُزال المهمة من القوائم النشطة ويبقى سجلها محفوظًا.",
  workChanged: "حُدثت المهمة",
  noteAdded: "أضاف ملاحظة",
  delivered: "قدّم العمل للمراجعة",
  assigned: "حدّث المسؤولية",
  reviewed: "راجع العمل",
  execution: "التفاصيل الهندسية",
  executionLinked: "عمل هندسي مرتبط",
  executionInactive: "لم يعد هذا التنفيذ نشطًا.",
  linkExecution: "ربط عمل هندسي قائم",
  workTaskId: "رقم المهمة الهندسية القائمة",
  linkHint: "اربط تنفيذًا نشطًا للوكيل المكلّف. لا يبدأ هذا محادثة أو نموذجًا.",
  noExecution:
    "لا يوجد تنفيذ هندسي مرتبط. يستطيع الأشخاص إنجاز هذا العمل مباشرةً.",
  sourceVersion: "النسخة",
  refreshBeforeRetry:
    "تعذّر تأكيد الحفظ. حدّث قائمة العمل قبل محاولة إنشاء مهمة أخرى.",
}

export function useBusinessCopy(): BusinessCopy {
  return useLocale() === "ar" ? arabic : english
}
