//! Task-owned exact-version disclosure. Reuses this store's current visibility,
//! human policy, references, CAS and immutable audit; Apache source in NOTICE.
use super::*;
use crate::business_execution::{
    common::Result as ExecutionResult,
    publication,
    types::{
        AuthorityKind, OperationReason, PublicProducer, Publication, PublishedAssetRef,
        PublishedInput, PublishedVersion, SubmissionActor, SubmitInput,
    },
    validation,
};

pub(super) async fn references_for_detail<C: ConnectionTrait>(
    conn: &C,
    row: &task::Model,
    deliverable_id: &str,
) -> Result<Vec<PublishedAssetRef>, E> {
    let rows = conn.query_all(statement(
        "SELECT v.asset_id,v.id,v.title,v.media_type,v.byte_size,v.sha256 FROM business_execution_publication p JOIN business_execution_asset_version v ON v.organization_id=p.organization_id AND v.task_id=p.task_id AND v.asset_id=p.asset_id AND v.id=p.version_id WHERE p.organization_id=? AND p.task_id=? AND p.deliverable_id=? ORDER BY p.ordinal",
        vec![row.organization_id.clone().into(), row.id.clone().into(), deliverable_id.into()],
    )).await?;
    rows.into_iter()
        .map(|r| {
            Ok(PublishedAssetRef {
                asset_id: r.try_get("", "asset_id")?,
                version_id: r.try_get("", "id")?,
                title: r.try_get("", "title")?,
                media_type: r.try_get("", "media_type")?,
                byte_size: r.try_get("", "byte_size")?,
                sha256: r.try_get("", "sha256")?,
            })
        })
        .collect()
}

/// Caller owns the identity writer and the exact operation receipt. The ID is
/// generated by that backend reservation, never a field accepted by the wire.
pub(crate) async fn submit_in_transaction(
    tx: &DatabaseTransaction,
    ctx: &ActorContext,
    input: &SubmitInput,
    deliverable_id: &str,
) -> ExecutionResult<Detail> {
    super::super::require_operator(ctx)?;
    validation::submit(input)?;
    validation::uuid(deliverable_id)?;
    let mut row = model(tx, ctx.principal.organization_id(), &input.task_id).await?;
    let actor = visible(tx, ctx, &row, Permission::Contribute).await?;
    require(actor.kind == MemberKind::Human && ctx.live.is_none())?;
    require(caps(tx, ctx, &row, &actor).await?.submit)?;
    if row.revision != input.expected_task_revision {
        return Err(E::Conflict.into());
    }
    references(tx, &row).await?;
    body(&input.body, false)?;
    for selected in &input.versions {
        publication::validate_selection(tx, &ctx.principal, &row.id, selected).await?;
    }
    tx.execute(statement(
        "INSERT INTO business_task_deliverable(id,organization_id,task_id,revision,author_id,author_name,author_kind,body,execution_id,created_at) VALUES(?,?,?,?,?,?,'human',?,NULL,?)",
        vec![deliverable_id.into(), row.organization_id.clone().into(), row.id.clone().into(),
            row.revision.checked_add(1).ok_or(E::Conflict)?.into(), actor.id.clone().into(),
            actor.display_name.clone().into(), input.body.clone().into(), now().into()],
    )).await?;
    for (ordinal, selected) in input.versions.iter().enumerate() {
        tx.execute(statement(
            "INSERT INTO business_execution_publication(organization_id,task_id,deliverable_id,asset_id,version_id,ordinal,authority_kind) VALUES(?,?,?,?,?,?,'operator')",
            vec![row.organization_id.clone().into(), row.id.clone().into(), deliverable_id.into(),
                selected.asset_id.clone().into(), selected.version_id.clone().into(), (ordinal as i64).into()],
        )).await?;
    }
    row.current_deliverable_id = Some(deliverable_id.into());
    row.status = TaskStatus::Review;
    Ok(finish_in_transaction(
        tx,
        ctx,
        row,
        &actor,
        "submitted",
        json!({"deliverableId": deliverable_id}),
    )
    .await?)
}

/// Private storage identity accompanies a safe public projection only inside the
/// backend. The byte reader must revalidate this same task reference.
pub(crate) struct Read {
    pub metadata: PublishedVersion,
    pub object_id: String,
}

pub(crate) async fn read_in_transaction(
    tx: &DatabaseTransaction,
    ctx: &ActorContext,
    input: &PublishedInput,
) -> ExecutionResult<Read> {
    for value in [
        &input.task_id,
        &input.deliverable_id,
        &input.asset_id,
        &input.version_id,
    ] {
        validation::uuid(value)?;
    }
    let row = model(tx, ctx.principal.organization_id(), &input.task_id).await?;
    visible(tx, ctx, &row, Permission::Read).await?;
    let record = tx.query_one(statement(
        "SELECT v.asset_id,v.id,v.title,v.media_type,v.byte_size,v.sha256,v.created_at,v.producer_client_id,v.producer_model,v.object_id,d.revision,d.author_id,d.author_name,p.authority_kind FROM business_execution_publication p JOIN business_execution_asset_version v ON v.organization_id=p.organization_id AND v.task_id=p.task_id AND v.asset_id=p.asset_id AND v.id=p.version_id JOIN business_task_deliverable d ON d.organization_id=p.organization_id AND d.task_id=p.task_id AND d.id=p.deliverable_id WHERE p.organization_id=? AND p.task_id=? AND p.deliverable_id=? AND p.asset_id=? AND p.version_id=?",
        vec![row.organization_id.into(), row.id.into(), input.deliverable_id.clone().into(),
            input.asset_id.clone().into(), input.version_id.clone().into()],
    )).await?.ok_or(OperationReason::Missing)?;
    let client_id: String = record.try_get("", "producer_client_id")?;
    let model: Option<String> = record.try_get("", "producer_model")?;
    // These are display labels, never a profile/config or session identifier.
    for label in std::iter::once(client_id.as_str()).chain(model.as_deref()) {
        if label.is_empty() || label.len() > 240 || label.chars().any(char::is_control) {
            return Err(OperationReason::Unavailable.into());
        }
    }
    let authority_kind = match record.try_get::<String>("", "authority_kind")?.as_str() {
        "operator" => AuthorityKind::Operator,
        "credential" => AuthorityKind::Credential,
        _ => return Err(OperationReason::Unavailable.into()),
    };
    Ok(Read {
        object_id: record.try_get("", "object_id")?,
        metadata: PublishedVersion {
            version: PublishedAssetRef {
                asset_id: record.try_get("", "asset_id")?,
                version_id: record.try_get("", "id")?,
                title: record.try_get("", "title")?,
                media_type: record.try_get("", "media_type")?,
                byte_size: record.try_get("", "byte_size")?,
                sha256: record.try_get("", "sha256")?,
            },
            created_at: record.try_get("", "created_at")?,
            producer: PublicProducer { client_id, model },
            publication: Publication {
                deliverable_id: input.deliverable_id.clone(),
                task_revision: record.try_get("", "revision")?,
                submitted_by: SubmissionActor {
                    member_id: record.try_get("", "author_id")?,
                    display_name: record.try_get("", "author_name")?,
                    authority_kind,
                },
            },
        },
    })
}
