async page => {
  await page.setViewportSize({width:1280,height:900})
  await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('light')
  await page.getByRole('button',{name:'Create task',exact:true}).first().click()
  const create=page.getByRole('dialog',{name:'Create task',exact:true})
  await create.getByLabel('Task title',{exact:true}).fill('Synthetic review: restricted feedback follow-up')
  await create.getByLabel('Brief',{exact:true}).fill('Synthetic feedback area content. Visible to authorized feedback members only.')
  await create.getByLabel('Area of work',{exact:true}).selectOption('feedback')
  const eligible=await create.getByLabel('Assigned to',{exact:true}).locator('option').allTextContents()
  if(eligible.some(s=>s.includes('Noura')))throw Error('Cross-domain member shown as eligible')
  const pending=page.waitForResponse(r=>r.url().endsWith('/api/business/tasks/create'))
  await create.getByRole('button',{name:'Create task',exact:true}).click()
  const response=await pending; const detail=await response.json()
  page.__privateTaskId=detail.task.id
  await page.getByRole('dialog',{name:detail.task.title,exact:true}).getByRole('button',{name:'Close',exact:true}).click()
  await page.getByLabel('Find a task',{exact:true}).fill('Synthetic review: no match sentinel')
  await page.getByLabel('Find a task',{exact:true}).press('Enter')
  await page.getByText('No tasks match these filters.',{exact:true}).waitFor()
  await page.screenshot({path:'reports/review-business-workspace-evidence/filter-empty-1280-light.png'})
  await page.getByRole('button',{name:'Clear filters',exact:true}).click()
  await page.getByRole('button',{name:/Synthetic review: restricted feedback follow-up/}).waitFor()
  await page.getByRole('combobox',{name:'Area of work',exact:true}).selectOption('marketing')
  await page.getByRole('button',{name:/Synthetic review: customer welcome brief/}).waitFor()
  const hiddenRestricted=await page.getByRole('button',{name:/Synthetic review: restricted feedback follow-up/}).count()===0
  await page.getByRole('combobox',{name:'Area of work',exact:true}).selectOption('')
  await page.getByRole('button',{name:'Board',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  const board=page.locator('div[aria-label="Board"][tabindex="0"]')
  await board.waitFor()
  await board.focus()
  await page.keyboard.press('ArrowRight')
  await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,400)))
  const boardGeometry=await board.evaluate(e=>({clientWidth:e.clientWidth,scrollWidth:e.scrollWidth,scrollLeft:e.scrollLeft,documentWidth:document.documentElement.scrollWidth,outline:getComputedStyle(e).outline}))
  await page.screenshot({path:'reports/review-business-workspace-evidence/board-390-light.png'})
  await page.getByRole('button',{name:'List',exact:true}).click()
  page.__failNextList=true
  await page.route('**/api/business/tasks/list',route=>{if(page.__failNextList){page.__failNextList=false;return route.abort('failed')}return route.continue()})
  await page.getByRole('button',{name:'Refresh',exact:true}).click()
  await page.getByText('The workspace could not be reached.',{exact:true}).waitFor()
  await page.screenshot({path:'reports/review-business-workspace-evidence/list-transport-error-390.png'})
  await page.getByRole('button',{name:'Try again',exact:true}).click()
  await page.getByRole('button',{name:/Synthetic review: restricted feedback follow-up/}).waitFor()
  return {privateTaskId:detail.task.id,privateTaskDomain:detail.task.domain,eligible,createdStatus:response.status(),emptySearch:true,hiddenRestricted,boardGeometry,errorKind:'One reviewer-guard-aborted list request; actual recovery response, no fake API JSON',retryRecovered:true,ledger:page.__businessReview}
}
